### ISSUE TITLE
Streaming iz arhiva oddaj

### ISSUE THREAD

**Issue by matejv** [dahool84/plugin.video.mmc#1]
Najprej, hvala za tale plugin. IMO je to nekaj, kar bi moral RTVSLO sam razvit in vzdrževat.

Sedaj pa težave: Na RTV so spremenili postopek za streaming iz arhiva oddaj. Na srečo so potrebni le manjši popravki kode v funkciji addFlash:
- videoUrl - rtmp://fms.rtvslo.si/ -> rtmp://stream.rtvslo.si/simplevideostreaming
- app=vod -> app=simplevideostreaming
- swfUrl=http://tvslo.si/media_player.swf -> swfUrl=http://tvslo.si/media_jwplayer_5.7.swf

Za ogled v živo pa v addFlashLive:
- rtmp://fms.rtvslo.si/live/ -> rtmp://stream.rtvslo.si/simplevideostreaming/live/
- swfUrl=http://tvslo.si/media_player.swf -> swfUrl=http://tvslo.si/media_jwplayer_5.7.swf

S temi popravki lahko spet gledam posnetke oddaj in programe v živo.

**Comment by dahool84** [comment]
Popravljeno. Hvala
